//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Process_System_HR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Applicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applicant()
        {
            this.Applicant_Vacancy = new HashSet<Applicant_Vacancy>();
        }
    

        [DisplayName("Applicant code")]
      
        public int ApId { get; set; }

        [MaxLength(50, ErrorMessage ="Up to 50 characters in length.")]
        public string Name { get; set; }
      
        [DataType(DataType.Date)]
        public System.DateTime Birthday { get; set; }
       
        public string Gender { get; set; }
    
        public string Address { get; set; }
        
        public string IdentifyCard { get; set; }
     
        public string Phone { get; set; }
      
        public string Email { get; set; }
    
        public string Major { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime DateCreated { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applicant_Vacancy> Applicant_Vacancy { get; set; }
    }
}
