//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Process_System_HR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Interviewers = new HashSet<Interviewer>();
            this.Vacancies = new HashSet<Vacancy>();
        }
    
        
        [DisplayName("Employee code")]
        public string EmployeeCode { get; set; }
        [DisplayName("Department code")]
        
        public string DepartmentCode { get; set; }
        
        public string Password { get; set; }
        
        public string Name { get; set; }
        [DataType(DataType.EmailAddress)]
        [MaxLength(25, ErrorMessage = "Email up to 25 character")]
        public string Email { get; set; }
        [DisplayName("Type")]
        
        public string Position { get; set; }

        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interviewer> Interviewers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacancy> Vacancies { get; set; }
    }
}
