//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Process_System_HR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Interview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Interview()
        {
            this.Interviewers = new HashSet<Interviewer>();
        }
    [DisplayName("Interviewer code")]
        
        public int InterID { get; set; }
       
        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }

        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        [DisplayName("App-Vac code")]
     
        public Nullable<int> VAId { get; set; }
    
        public virtual Applicant_Vacancy Applicant_Vacancy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interviewer> Interviewers { get; set; }
    }
}
