//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Process_System_HR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Vacancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacancy()
        {
            this.Applicant_Vacancy = new HashSet<Applicant_Vacancy>();
        }
    
        [DisplayName("Vacancy code")]

        public string VacId { get; set; }
        [DisplayName("Employee code")]
    
        public string EmployeeCode { get; set; }
        [DataType(DataType.Date)]
    
        public System.DateTime DateBegin { get; set; }
        public string status { get; set; }
        [MaxLength(100, ErrorMessage ="Up to 100 characters in length.")]
        public string Title { get; set; }
     
        public string Description { get; set; }
    
        public string RequireDescription { get; set; }
     
        public string Benefit { get; set; }
        [Range(5,50,ErrorMessage ="quality must between 5 to 50")]
        public int Quantity { get; set; }
        [DisplayName("Department code")]
        public string DepartmentCode { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateOfChangeStatus { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FulfillDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applicant_Vacancy> Applicant_Vacancy { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
